In [41]:
import numpy as np

arr = [(160, 'F'), (165, 'F'), (155, 'F'), (172, 'F'), (175, 'B'), (180, 'B'), (177, 'B'), (190, 'B')]

heights = [h for h, l in arr]
labels =  [l for h, l in arr]

bins = np.linspace(start=150, stop=191, num=5)
heights = np.digitize(heights, bins) - 1


height = 178
height = np.digitize(height, bins) - 1

unique, counts = np.unique(labels, return_counts=True)

boy_count = np.sum([1 for l in labels if l == 'B'])
girl_count = np.sum([1 for l in labels if l == 'F'])

prob_boy = boy_count / len(labels)
prob_girl = girl_count / len(labels)

count_boys_height = np.sum([1 for (h, l) in zip(heights, labels) if l == 'B' and h == height])
count_girls_height = np.sum([1 for (h, l) in zip(heights, labels) if l == 'F' and h == height])

prob_boy_height = count_boys_height / boy_count
prob_girl_height = count_girls_height / girl_count

prob_height = np.sum([1 for (h, l) in zip(heights, labels) if h == height]) / len(labels)


print(prob_boy_height * prob_boy / prob_height)
print(prob_girl_height * prob_girl / prob_height)


0.75
0.25


In [43]:
def values_to_bins(arr, bins):
    ar = np.digitize(arr, bins) - 1
    return arr

In [50]:
import numpy as np
import matplotlib.pyplot as plt
train_images = np.loadtxt('data/train_images.txt') # incarcam imaginile
train_labels = np.loadtxt('data/train_labels.txt', 'int', converters=float) 

test_images = np.loadtxt('data/test_images.txt') # incarcam imaginile
test_labels = np.loadtxt('data/test_labels.txt', 'int', converters=float) 

num_bins = 5
bins = np.linspace(start=0, stop = 256, num=num_bins+1)

train_images = values_to_bins(train_images, bins)
test_images = values_to_bins(test_images, bins)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [51]:
from sklearn.naive_bayes import MultinomialNB
naive_bayes_model = MultinomialNB()
naive_bayes_model.fit(train_images, train_labels)
naive_bayes_model.score(test_images, test_labels)

0.846

In [54]:
prediction = naive_bayes_model.predict(test_images)
conf_matrix = np.zeros((10, 10))

for p, l in zip(prediction, test_labels):
    conf_matrix[p][l] += 1

print(*conf_matrix, sep="\n")

[51.  0.  2.  0.  0.  1.  1.  0.  0.  0.]
[ 0. 48.  0.  0.  0.  0.  0.  1.  1.  0.]
[ 0.  0. 51.  1.  0.  0.  0.  0.  3.  1.]
[ 0.  0.  1. 49.  0.  9.  0.  0.  3.  1.]
[ 0.  0.  1.  0. 34.  0.  1.  1.  1.  5.]
[ 0.  0.  0.  0.  0. 35.  0.  0.  1.  0.]
[ 1.  0.  0.  0.  0.  1. 44.  0.  1.  0.]
[ 0.  0.  1.  0.  0.  1.  0. 42.  1.  0.]
[ 1.  4.  1.  0.  2.  5.  2.  0. 34.  0.]
[ 0.  0.  1.  3. 10.  0.  0.  6.  1. 35.]
